name: flake8 Lint

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Flake8 Lint
        uses: py-actions/flake8@v2
        with:
            path: "./Software/Testing"
            ignore: "E501,E203,E722" #Ignore line to long, we don't care

      - name: Black File Formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./Software/Testing"

      - name: Flake8 Lint Production
        uses: py-actions/flake8@v2
        with:
            path: "./Software/Production"
            ignore: "E501,E203,E722" #Ignore line to long, we don't care

      - name: Black File Formatter Production
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./Software/Production"
